# This postcondition asserts that the `return_value` is generated by applying a two-step transformation to each character of the `message`. The first step swaps the case of the character (uppercase to lowercase, lowercase to uppercase, non-letters remain unchanged). The second step then replaces any vowels in the *result* of the first step with the letter two places ahead in the alphabet, otherwise keeping the character unchanged.
assert return_value == "".join(map(lambda char_original: (chr(ord(
    (chr(ord(char_original) + 32) if 'A' <= char_original <= 'Z' else
     (chr(ord(char_original) - 32) if 'a' <= char_original <= 'z' else
      char_original))
)) + 2) if (
    (chr(ord(char_original) + 32) if 'A' <= char_original <= 'Z' else
     (chr(ord(char_original) - 32) if 'a' <= char_original <= 'z' else
      char_original))
) in "aeiouAEIOU" else (
    (chr(ord(char_original) + 32) if 'A' <= char_original <= 'Z' else
     (chr(ord(char_original) - 32) if 'a' <= char_original <= 'z' else
      char_original))
), message))


