def encode_original(message):
    """
    Write a function that takes a message, and encodes in such a 
    way that it swaps case of all letters, replaces all vowels in 
    the message with the letter that appears 2 places ahead of that 
    vowel in the english alphabet. 
    Assume only letters. 
    
    Examples:
    >>> encode('test')
    'TGST'
    >>> encode('This is a message')
    'tHKS KS C MGSSCGG'
    """

    def switch_case(ch):
        if ord('A') <= ord(ch) <= ord('Z'):
            return chr(ord(ch) + 32)
        elif ord('a') <= ord(ch) <= ord('z'):
            return chr(ord(ch) - 32)
        else:
            return ch

    def vowel_change(ch):
        return ch if ch not in 'aeiouAEIOU' else chr(ord(ch) + 2)
    m = ''.join(map(switch_case, message))
    return ''.join(map(vowel_change, m))


def encode(message):


    return_value = encode_original(message)
    
    # Adding imports that might be useful for postconditions
    import re 
    # This postcondition asserts that the `return_value` is generated by applying a two-step transformation to each character of the `message`. The first step swaps the case of the character (uppercase to lowercase, lowercase to uppercase, non-letters remain unchanged). The second step then replaces any vowels in the *result* of the first step with the letter two places ahead in the alphabet, otherwise keeping the character unchanged.
    assert return_value == "".join(map(lambda char_original: (chr(ord(
        (chr(ord(char_original) + 32) if 'A' <= char_original <= 'Z' else
         (chr(ord(char_original) - 32) if 'a' <= char_original <= 'z' else
          char_original))
    )) + 2) if (
        (chr(ord(char_original) + 32) if 'A' <= char_original <= 'Z' else
         (chr(ord(char_original) - 32) if 'a' <= char_original <= 'z' else
          char_original))
    ) in "aeiouAEIOU" else (
        (chr(ord(char_original) + 32) if 'A' <= char_original <= 'Z' else
         (chr(ord(char_original) - 32) if 'a' <= char_original <= 'z' else
          char_original))
    ), message))

    return return_value
