experiment:
  model: models/gemini-2.5-flash
  temperature: 0.7
  n_model_responses: 1
  n_per_model_call: 1
  to_generate: postcondition
  samplesFolder: llm_gen_outputs/1
  has_reference_code: true
  prompt_v: base
  system_prompt: You are a programming assistant that generates executable python
    only. You generate correct code, so you only generate code you are sure of. You
    have Python comments explaining your intent when possible.
api:
  name: gemini
  key: GEMINI_API_KEY
benchmarks:
  name: evalplus
  run_all: false
  run_only:
  - 159
  - 160
  - 161
  - 162
  - 163
  run_except: []
  run_range: true
  run_start: HumanEval/159
  run_end: HumanEval/163
